### PR TITLE
Add SwipeBehavior (Bot API 7.7)

### PR DESCRIPTION
**Pull request by qeeqez**
# Add SwipeBehavior (Bot API 7.7)

### Add SwipeBehavior component for Telegram Bot API 7.7 support

- Implement new SwipeBehavior component to interface with Telegram's WebApp
- Add `isVerticalSwipesEnabled` property to SwipeBehavior
- Implement `enableVerticalSwipes()` method in SwipeBehavior
- Implement `disableVerticalSwipes()` method in SwipeBehavior

### Code added in [telegram-web-app.js](https://telegram.org/js/telegram-web-app.js):
```js
var isVerticalSwipesEnabled = true;
WebApp.enableVerticalSwipes = function() {
  WebApp.isVerticalSwipesEnabled = true;
};
WebApp.disableVerticalSwipes = function() {
  WebApp.isVerticalSwipesEnabled = false;
};
Object.defineProperty(WebApp, 'isVerticalSwipesEnabled', {
    set: function(val){ toggleVerticalSwipes(val); },
    get: function(){ return isVerticalSwipesEnabled; },
    enumerable: true
});
function toggleVerticalSwipes(enable_swipes) {
  if (!versionAtLeast('7.7')) {
    console.warn('[Telegram.WebApp] Changing swipes behavior is not supported in version ' + webAppVersion);
    return;
  }
  isVerticalSwipesEnabled = !!enable_swipes;
  WebView.postEvent('web_app_setup_swipe_behavior', false, {allow_vertical_swipe: isVerticalSwipesEnabled});
}
 ```

### CODE REVIEW

**Comment by heyqbnk** [comment]
Oh my god. I am sorry, I didn't see you Pull Request. It seems like we did actually almost the same changes:
https://github.com/Telegram-Mini-Apps/telegram-apps/pull/392

**Comment by heyqbnk** [comment]
You can open a PR with the `swipe-behavior.md` and docs changes related to SDK bindings

**Comment by qeeqez** [comment]
No problem at all. Waited for this feature from telegram for too long 😅

I'll do pr for docs in few mins

**Comment by diandiandiandedian** [comment]
Do I need to wait for a new version of Telegram to use this feature on my iPhone?​

**Comment by qeeqez** [comment]
> Do I need to wait for a new version of Telegram to use this feature on my iPhone?​

Yes, we need to wait for App Store and Google Store update. Now our apps report API version 7.6

**Pull request closed without merging**
