### PR TITLE
feat(sdk-svelte-playground): playground for sdk-svelt added

### PR DESCRIPTION
**Pull request by ugrinovsky**
I still need to configure the linter (I have some problems with it) and tidy up the code a bit

After that, you can copy it to another repository for the template.

UPDATE.
Playground eslint is configured.

### CODE REVIEW

**Review by Fart10 — CHANGES_REQUESTED** [review]
🙏🏻

**Comment by heyqbnk** [comment]
Hi! Could you rebase `master`? We had a big update there

**Comment by Fart10** [comment]
Sorry guys ffor the long reply 🤯

**Comment by heyqbnk** [comment]
Thank you! <3

**Pull request merged**
